import halloWorld from "../asset/carrousel/hallo-word-card.jpg";

export const allAnime = [
  {
    name: "Hello World",
    rates: 3,
    genre: "Drama, Romance, Sci-fi",
    duration: "1:37min",
    resolution: "HD-1009",
    pic: halloWorld,
  },
  {
    name: "Hello World",
    rates: 3,
    genre: "Drama, Romance, Sci-fi",
    duration: "1:37min",
    resolution: "HD-1009",
    pic: halloWorld,
  },
  {
    name: "Hello World",
    rates: 3,
    genre: "Drama, Romance, Sci-fi",
    duration: "1:37min",
    resolution: "HD-1009",
    pic: halloWorld,
  },
  {
    name: "Hello World",
    rates: 3,
    genre: "Drama, Romance, Sci-fi",
    duration: "1:37min",
    resolution: "HD-1009",
    pic: halloWorld,
  },
  {
    name: "Hello World",
    rates: 3,
    genre: "Drama, Romance, Sci-fi",
    duration: "1:37min",
    resolution: "HD-1009",
    pic: halloWorld,
  },
  {
    name: "Hello World",
    rates: 3,
    genre: "Drama, Romance, Sci-fi",
    duration: "1:37min",
    resolution: "HD-1009",
    pic: halloWorld,
  },
  {
    name: "Hello World",
    rates: 3,
    genre: "Drama, Romance, Sci-fi",
    duration: "1:37min",
    resolution: "HD-1009",
    pic: halloWorld,
  },
  {
    name: "Hello World",
    rates: 3,
    genre: "Drama, Romance, Sci-fi",
    duration: "1:37min",
    resolution: "HD-1009",
    pic: halloWorld,
  },
  {
    name: "Hello World",
    rates: 3,
    genre: "Drama, Romance, Sci-fi",
    duration: "1:37min",
    resolution: "HD-1009",
    pic: halloWorld,
  },
  {
    name: "Hello World",
    rates: 3,
    genre: "Drama, Romance, Sci-fi",
    duration: "1:37min",
    resolution: "HD-1009",
    pic: halloWorld,
  },
  {
    name: "Hello World",
    rates: 3,
    genre: "Drama, Romance, Sci-fi",
    duration: "1:37min",
    resolution: "HD-1009",
    pic: halloWorld,
  },
  {
    name: "Hello World",
    rates: 3,
    genre: "Drama, Romance, Sci-fi",
    duration: "1:37min",
    resolution: "HD-1009",
    pic: halloWorld,
  },
  {
    name: "Hello World",
    rates: 3,
    genre: "Drama, Romance, Sci-fi",
    duration: "1:37min",
    resolution: "HD-1009",
    pic: halloWorld,
  },
  {
    name: "Hello World",
    rates: 3,
    genre: "Drama, Romance, Sci-fi",
    duration: "1:37min",
    resolution: "HD-1009",
    pic: halloWorld,
  },
  {
    name: "Hello World",
    rates: 3,
    genre: "Drama, Romance, Sci-fi",
    duration: "1:37min",
    resolution: "HD-1009",
    pic: halloWorld,
  },
  {
    name: "Hello World",
    rates: 3,
    genre: "Drama, Romance, Sci-fi",
    duration: "1:37min",
    resolution: "HD-1009",
    pic: halloWorld,
  },
  {
    name: "Hello World",
    rates: 3,
    genre: "Drama, Romance, Sci-fi",
    duration: "1:37min",
    resolution: "HD-1009",
    pic: halloWorld,
  },
];
